### PR TITLE
Don't try to marshal non-serializable variables

### LINKED ISSUE #7734: Object with finalizer dumps wrong data leading to: `load': marshal data too short`
**Environment Information**
  
jruby 9.4.2.0 (3.1.0) 2023-03-21 90d2913fda OpenJDK 64-Bit Server VM 11.0.18+10-post-Ubuntu-0ubuntu122.04 on 11.0.18+10-post-Ubuntu-0ubuntu122.04 +jit [x86_64-linux]

Older JRubies are affected equally.

**Expected Behavior**

This can be done in irb:

```ruby
a = ""   # => "" 
ObjectSpace.define_finalizer(a, Kernel.method(:puts))   # => [0, #<Method: Kernel.puts(*)>] 
Marshal.load(Marshal.dump(a))  # => ""
```

This expectation is met on MRI and on TruffleRuby.

**Actual Behavior**

JRuby dumps wrong marshal data when a finalizer is set on the object to be marshaled. It doesn't matter what kind of object it is or which method is set as the finalizer.

```ruby
a = ""   # => "" 
ObjectSpace.define_finalizer(a, Kernel.method(:puts))   # => [0, #<Method: Kernel.puts(*)>] 
Marshal.load(Marshal.dump(a))

`org/jruby/RubyMarshal.java:149:in `load': marshal data too short (ArgumentError)
        from (irb):13:in `evaluate'                            
        from org/jruby/RubyKernel.java:1143:in `eval'          
	from org/jruby/RubyKernel.java:1586:in `loop'
	from org/jruby/RubyKernel.java:1292:in `catch'
	from org/jruby/RubyKernel.java:1292:in `catch'
	from /home/local/COMCARD-NT/kanis/.rvm/rubies/jruby-9.4.2.0/bin/irb:13:in `<main>'`

# here is the difference:
Marshal.dump(a)  # => "\x04\bI\"\x00\a:\x06ET" 
Marshal.dump("") # => "\x04\bI\"\x00\x06:\x06ET" 

```

### PR DESCRIPTION
**Pull request by headius**
This fixes #7734 by not confusing the finalizer with marshalable state.

### CODE REVIEW

File: spec/ruby/core/marshal/dump_spec.rb [hunk 1]
```diff
@@ -458,6 +458,12 @@ def obj.foo; end
       obj = MarshalSpec::BasicObjectSubWithRespondToFalse.new
       Marshal.dump(obj).should == "\x04\bo:2MarshalSpec::BasicObjectSubWithRespondToFalse\x00"
     end
+
+    it "dumps without marshaling any attached finalizer" do
+      obj = Object.new
+      ObjectSpace.define_finalizer(obj, &:itself)
```
Comment (eregon) [inline spec/ruby/core/marshal/dump_spec.rb:464]: FYI this causes:
```
1)
Marshal.dump with an Object dumps without marshaling any attached finalizer ERROR
ArgumentError: Can't create Binding from C level Proc
/home/eregon/code/rubyspec/core/marshal/dump_spec.rb:464:in `define_finalizer'
/home/eregon/code/rubyspec/core/marshal/dump_spec.rb:464:in `block (3 levels) in <top (required)>'
/home/eregon/code/rubyspec/core/marshal/dump_spec.rb:6:in `<top (required)>'
[| | ==================100%================== | 00:00:00]      0F      1E 
```
on CRuby 3.0+. Just on 2.7 it seems to work.
I modified the spec a bit to make it work on all CRuby versions: https://github.com/ruby/spec/commit/d44cd79a85cfd1293d08987692c5c0522b197ffa
