### PR TITLE
Launcher: Defensive fixes

### LINKED ISSUE #8747: Launcher script chokes on GraalVM release file
Builds of GraalVM contain a release file with an unquoted, json-formatted `COMMIT_INFO` line that is not cannot be evaluated by a shell. This leads to the following output when attempting to use GraalVM with the current jruby.sh launcher:

```
[] jruby $ JAVA_HOME=~/java/graalvm-jdk-24+36.1/Contents/Home jruby bench_ractors_tarai.rb
/Users/headius/java/graalvm-jdk-24+36.1/Contents/Home/release: line 11: {commit.committer:: command not found
/Users/headius/work/jruby/bin/jruby: line 515: [: : integer expression expected
/Users/headius/work/jruby/bin/jruby: line 526: [: : integer expression expected
/Users/headius/work/jruby/bin/jruby: line 534: [: : integer expression expected
/Users/headius/work/jruby/bin/jruby: line 542: [: : integer expression expected
WARNING: A restricted method in java.lang.System has been called
WARNING: java.lang.System::load has been called by com.kenai.jffi.internal.StubLoader in module org.jruby.dist (file:/Users/headius/work/jruby/lib/jruby.jar)
WARNING: Use --enable-native-access=org.jruby.dist to avoid a warning for callers in this module
WARNING: Restricted methods will be blocked in a future release unless native access is enabled

WARNING: A terminally deprecated method in sun.misc.Unsafe has been called
WARNING: sun.misc.Unsafe::putLong has been called by com.kenai.jffi.UnsafeMemoryIO$UnsafeMemoryIO64 (file:/Users/headius/work/jruby/lib/jruby.jar)
WARNING: Please consider reporting this to the maintainers of class com.kenai.jffi.UnsafeMemoryIO$UnsafeMemoryIO64
WARNING: sun.misc.Unsafe::putLong will be removed in a future release
```

Here's the `release` file from my recent download:

```
IMPLEMENTOR="Oracle Corporation"
JAVA_RUNTIME_VERSION="24+36-jvmci-b01"
JAVA_VERSION="24"
JAVA_VERSION_DATE="2025-03-18"
LIBC="default"
MODULES="java.base java.logging java.management jdk.internal.vm.ci org.graalvm.collections org.graalvm.word org.graalvm.nativeimage jdk.management jdk.unsupported org.graalvm.truffle.compiler jdk.graal.compiler com.oracle.graal.graal_enterprise com.oracle.svm.enterprise.truffle java.compiler java.datatransfer java.xml java.prefs java.desktop java.instrument java.security.sasl java.naming java.rmi java.management.rmi java.net.http java.scripting java.security.jgss java.transaction.xa java.sql java.sql.rowset java.xml.crypto java.se java.smartcardio jdk.accessibility jdk.internal.jvmstat jdk.attach jdk.charsets jdk.internal.opt jdk.zipfs jdk.compiler jdk.crypto.cryptoki jdk.crypto.ec jdk.dynalink jdk.internal.ed jdk.editpad jdk.graal.compiler.management jdk.hotspot.agent jdk.httpserver jdk.incubator.vector jdk.internal.le jdk.internal.md jdk.jartool jdk.javadoc jdk.jcmd jdk.management.agent jdk.jconsole jdk.jdeps jdk.jdwp.agent jdk.jdi jdk.jfr jdk.jlink jdk.jpackage jdk.jshell jdk.jsobject jdk.jstatd jdk.localedata jdk.management.jfr jdk.naming.dns jdk.naming.rmi jdk.net jdk.nio.mapmode jdk.sctp jdk.security.auth jdk.security.jgss jdk.unsupported.desktop jdk.xml.dom org.graalvm.nativeimage.llvm"
OS_ARCH="aarch64"
OS_NAME="Darwin"
SOURCE=".:git:febf65d41a22 open:git:47fc4b79f32f labsjdk-builder:a2c0cc958a47161f5a6c8439d25776f83a53e14e compiler:7b230f23574c51bae4b1b13802a02095874cf7bc graal-enterprise:b3eef60a91008ec918ac9ec36c3d4ec1c0fe1d3e regex:7b230f23574c51bae4b1b13802a02095874cf7bc sdk:7b230f23574c51bae4b1b13802a02095874cf7bc substratevm:7b230f23574c51bae4b1b13802a02095874cf7bc substratevm-enterprise:b3eef60a91008ec918ac9ec36c3d4ec1c0fe1d3e substratevm-enterprise-gcs:2ea883e9faf8bd00da4c0f7592214eee01702479 tools:7b230f23574c51bae4b1b13802a02095874cf7bc truffle:7b230f23574c51bae4b1b13802a02095874cf7bc vm:7b230f23574c51bae4b1b13802a02095874cf7bc vm-enterprise:b3eef60a91008ec918ac9ec36c3d4ec1c0fe1d3e wasm:7b230f23574c51bae4b1b13802a02095874cf7bc web-image:b3eef60a91008ec918ac9ec36c3d4ec1c0fe1d3e web-image-enterprise:b3eef60a91008ec918ac9ec36c3d4ec1c0fe1d3e"
GRAALVM_VERSION="24.2.0"
COMMIT_INFO={"compiler": {"commit.committer": "Danilo Ansaloni <danilo.ansaloni@oracle.com>", "commit.committer-ts": 1741116591, "commit.rev": "7b230f23574c51bae4b1b13802a02095874cf7bc"}, "graal-enterprise": {"commit.committer": "Danilo Ansaloni <danilo.ansaloni@oracle.com>", "commit.committer-ts": 1741116591, "commit.rev": "b3eef60a91008ec918ac9ec36c3d4ec1c0fe1d3e"}, "regex": {"commit.committer": "Danilo Ansaloni <danilo.ansaloni@oracle.com>", "commit.committer-ts": 1741116591, "commit.rev": "7b230f23574c51bae4b1b13802a02095874cf7bc"}, "sdk": {"commit.committer": "Danilo Ansaloni <danilo.ansaloni@oracle.com>", "commit.committer-ts": 1741116591, "commit.rev": "7b230f23574c51bae4b1b13802a02095874cf7bc"}, "substratevm": {"commit.committer": "Danilo Ansaloni <danilo.ansaloni@oracle.com>", "commit.committer-ts": 1741116591, "commit.rev": "7b230f23574c51bae4b1b13802a02095874cf7bc"}, "substratevm-enterprise": {"commit.committer": "Danilo Ansaloni <danilo.ansaloni@oracle.com>", "commit.committer-ts": 1741116591, "commit.rev": "b3eef60a91008ec918ac9ec36c3d4ec1c0fe1d3e"}, "substratevm-enterprise-gcs": {"commit.committer": "Peter Hofer <peter.hofer@oracle.com>", "commit.committer-ts": 1733135770, "commit.rev": "2ea883e9faf8bd00da4c0f7592214eee01702479"}, "tools": {"commit.committer": "Danilo Ansaloni <danilo.ansaloni@oracle.com>", "commit.committer-ts": 1741116591, "commit.rev": "7b230f23574c51bae4b1b13802a02095874cf7bc"}, "truffle": {"commit.committer": "Danilo Ansaloni <danilo.ansaloni@oracle.com>", "commit.committer-ts": 1741116591, "commit.rev": "7b230f23574c51bae4b1b13802a02095874cf7bc"}, "vm": {"commit.committer": "Danilo Ansaloni <danilo.ansaloni@oracle.com>", "commit.committer-ts": 1741116591, "commit.rev": "7b230f23574c51bae4b1b13802a02095874cf7bc"}, "vm-enterprise": {"commit.committer": "Danilo Ansaloni <danilo.ansaloni@oracle.com>", "commit.committer-ts": 1741116591, "commit.rev": "b3eef60a91008ec918ac9ec36c3d4ec1c0fe1d3e"}, "wasm": {"commit.committer": "Danilo Ansaloni <danilo.ansaloni@oracle.com>", "commit.committer-ts": 1741116591, "commit.rev": "7b230f23574c51bae4b1b13802a02095874cf7bc"}, "web-image": {"commit.committer": "Danilo Ansaloni <danilo.ansaloni@oracle.com>", "commit.committer-ts": 1741116591, "commit.rev": "b3eef60a91008ec918ac9ec36c3d4ec1c0fe1d3e"}, "web-image-enterprise": {"commit.committer": "Danilo Ansaloni <danilo.ansaloni@oracle.com>", "commit.committer-ts": 1741116591, "commit.rev": "b3eef60a91008ec918ac9ec36c3d4ec1c0fe1d3e"}}
```

I will file a bug with GraalVM, but even if they fix this there will still be bad files in the wild for some time (and they may decide not to fix it). We'll need to parse the file rather than just loading it as env.

### PR DESCRIPTION
**Pull request by mrnoname1000**
Added some checks to the launcher to handle missing `HOME`, `JAVA_HOME`, or argument to `-{C,e,I,S}`

Fixes #8747

### CODE REVIEW

File: bin/jruby.sh [hunk 1]
```diff
@@ -473,6 +482,11 @@ dir_name "$JAVACMD"
 dir_name "$REPLY"
 JAVA_HOME="$REPLY"
 
+if ! [ -e "$JAVA_HOME/release" ]; then
```
Comment (headius) [inline bin/jruby.sh:485]: This is fine for JRuby 10 but it will not work with JRuby 9.4 when we backport the script.

**Review by headius — COMMENTED** [review]
I think we need to detect whether we found a JAVA_HOME a different way that works without the release file; perhaps `$JAVA_HOME/bin/java`?

File: bin/jruby.sh (hunk 1 above)
Comment (mrnoname1000) [reply bin/jruby.sh]: Your most recent changes handle this better so I removed this

**Comment by mrnoname1000** [comment]
Added some code to parse `$JAVA_HOME/release` instead of source it, which lets us use `$JAVA_RELEASE_VERSION` for the AppCDS archive which may be more correct and will handle Graal better

**Comment by headius** [comment]
@mrnoname1000 Please re-review this... it's been sitting for a few months and I want to make sure it's still valid.

**Comment by mrnoname1000** [comment]
Weirdly enough the last commit to the launcher in master was less than an hour before the first one in this branch, so no conflicts and everything still looks valid

**Comment by headius** [comment]
@mrnoname1000 Thanks, merged!
