### PR TITLE
Fixes #5517 (returns in unexpected place)

### LINKED ISSUE #5517: NPE due to unhandled non-local return
### Environment

* JRuby: `jruby 9.2.5.0 (2.5.0) 2018-12-06 6d5a228 OpenJDK 64-Bit Server VM 25.181-b13 on 1.8.0_181-b13 +jit [linux-x86_64]`
* OS: `Linux rails.r4 3.16.0-5-amd64 #1 SMP Debian 3.16.51-3+deb8u1 (2018-01-08) x86_64 Linux`
* Environment variables:

```
JRUBY_VERSION=9.2.5.0
JAVA_ALPINE_VERSION=8.181.13-r0
JAVA_OPTS=-Xms1G -Xmx1G -XX:ReservedCodeCacheSize=128M -XX:+UseCodeCacheFlushing -Duser.timezone=GMT -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/logs -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dorg.apache.camel.jmx.serviceUrlPath="/jmxrmi" -Dcom.sun.management.jmxremote.port=9073
JRUBY_OPTS=--server  -Xjit.threshold=5 -Xjit.max=16384
```

### Exception:

<details>
<summary>Click to expand</summary>

```
Java::JavaLang::NullPointerException ():

org.jruby.ir.runtime.IRRuntimeHelpers.checkForLJE(IRRuntimeHelpers.java:125)
org.jruby.ir.instructions.CheckForLJEInstr.check(CheckForLJEInstr.java:69)
org.jruby.ir.interpreter.StartupInterpreterEngine.processOtherOp(StartupInterpreterEngine.java:171)
org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:104)
org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:128)
org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:151)
org.jruby.runtime.IRBlockBody.doYield(IRBlockBody.java:194)
org.jruby.runtime.BlockBody.yield(BlockBody.java:125)
org.jruby.runtime.Block.yieldArray(Block.java:177)
org.jruby.RubyBasicObject.yieldUnder(RubyBasicObject.java:1762)
org.jruby.RubyBasicObject.instance_exec(RubyBasicObject.java:2666)
org.jruby.RubyBasicObject$INVOKER$i$0$3$instance_exec.call(RubyBasicObject$INVOKER$i$0$3$instance_exec.gen)
org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:303)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:84)
org.jruby.ir.instructions.CallBase.interpret(CallBase.java:547)
org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:362)
org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:128)
org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:151)
org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:79)
org.jruby.runtime.Block.call(Block.java:124)
org.jruby.RubyProc.call(RubyProc.java:286)
org.jruby.RubyProc.call(RubyProc.java:266)
org.jruby.RubyProc$INVOKER$i$0$0$call.call(RubyProc$INVOKER$i$0$0$call.gen)
org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:203)
org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:199)
org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:346)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:172)
org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:317)
org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:92)
org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:204)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:191)
org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:207)
org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:367)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:203)
org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:326)
org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:86)
org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:171)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:158)
org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:199)
org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:346)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:172)
usr.src.app.vendor.bundle.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_controller.metal.rescue.invokeOther7:rescue_with_handler(vendor/bundle/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal/rescue.rb:25)
usr.src.app.vendor.bundle.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_controller.metal.rescue.RUBY$method$process_action$0(vendor/bundle/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal/rescue.rb:25)
org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:91)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:90)
org.jruby.ir.runtime.IRRuntimeHelpers.unresolvedSuper(IRRuntimeHelpers.java:1151)
org.jruby.ir.runtime.IRRuntimeHelpers.zSuperSplatArgs(IRRuntimeHelpers.java:1159)
usr.src.app.vendor.bundle.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_controller.metal.instrumentation.invokeSuper3:-unknown-super-target-(vendor/bundle/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal/instrumentation.rb:38)
usr.src.app.vendor.bundle.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_controller.metal.instrumentation.RUBY$block$process_action$1(vendor/bundle/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal/instrumentation.rb:38)
org.jruby.runtime.CompiledIRBlockBody.yieldDirect(CompiledIRBlockBody.java:146)
org.jruby.runtime.BlockBody.yield(BlockBody.java:114)
org.jruby.runtime.Block.yield(Block.java:165)
org.jruby.ir.runtime.IRRuntimeHelpers.yield(IRRuntimeHelpers.java:464)
org.jruby.ir.targets.YieldSite.yield(YieldSite.java:105)
usr.src.app.vendor.bundle.jruby.$2_dot_5_dot_0.gems.activesupport_minus_5_dot_2_dot_1.lib.active_support.notifications.RUBY$block$instrument$1(vendor/bundle/jruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/notifications.rb:168)
org.jruby.runtime.CompiledIRBlockBody.yieldDirect(CompiledIRBlockBody.java:146)
org.jruby.runtime.BlockBody.yield(BlockBody.java:114)
org.jruby.runtime.Block.yield(Block.java:165)
org.jruby.ir.runtime.IRRuntimeHelpers.yield(IRRuntimeHelpers.java:464)
org.jruby.ir.targets.YieldSite.yield(YieldSite.java:105)
usr.src.app.vendor.bundle.jruby.$2_dot_5_dot_0.gems.activesupport_minus_5_dot_2_dot_1.lib.active_support.notifications.instrumenter.RUBY$method$instrument$0(vendor/bundle/jruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/notifications/instrumenter.rb:23)
org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:91)
org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:127)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:189)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:211)
org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:220)
usr.src.app.vendor.bundle.jruby.$2_dot_5_dot_0.gems.activesupport_minus_5_dot_2_dot_1.lib.active_support.notif
ications.invokeOther5:instrument(vendor/bundle/jruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/notifications.rb:168)
usr.src.app.vendor.bundle.jruby.$2_dot_5_dot_0.gems.activesupport_minus_5_dot_2_dot_1.lib.active_support.notifications.RUBY$method$instrument$0(vendor/bundle/jruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/notifications.rb:168)
org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:91)
org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:127)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:189)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:211)
org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:220)
usr.src.app.vendor.bundle.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_controller.metal.instrumentation.invokeOther43:instrument(vendor/bundle/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal/instrumentation.rb:32)
usr.src.app.vendor.bundle.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_controller.metal.instrumentation.RUBY$method$process_action$0(vendor/bundle/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal/instrumentation.rb:32)
org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:91)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:90)
org.jruby.ir.runtime.IRRuntimeHelpers.unresolvedSuper(IRRuntimeHelpers.java:1151)
org.jruby.ir.runtime.IRRuntimeHelpers.unresolvedSuperSplatArgs(IRRuntimeHelpers.java:1133)
usr.src.app.vendor.bundle.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_controller.metal.params_wrapper.invokeSuper20:-unknown-super-target-(vendor/bundle/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal/params_wrapper.rb:256)
usr.src.app.vendor.bundle.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_controller.metal.params_wrapper.RUBY$method$process_action$0(vendor/bundle/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal/params_wrapper.rb:256)
org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:91)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:90)
org.jruby.ir.runtime.IRRuntimeHelpers.unresolvedSuper(IRRuntimeHelpers.java:1151)
usr.src.app.vendor.bundle.jruby.$2_dot_5_dot_0.gems.activerecord_minus_5_dot_2_dot_1.lib.active_record.railties.controller_runtime.invokeSuper1:-unknown-super-target-(vendor/bundle/jruby/2.5.0/gems/activerecord-5.2.1/lib/active_record/railties/controller_runtime.rb:24)
usr.src.app.vendor.bundle.jruby.$2_dot_5_dot_0.gems.activerecord_minus_5_dot_2_dot_1.lib.active_record.railties.controller_runtime.RUBY$method$process_action$0(vendor/bundle/jruby/2.5.0/gems/activerecord-5.2.1/lib/active_record/railties/controller_runtime.rb:24)
org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:91)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:90)
org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:173)
org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:314)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:74)
usr.src.app.vendor.bundle.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.abstract_controller.base.invokeOther11:process_action(vendor/bundle/jruby/2.5.0/gems/actionpack-5.2.1/lib/abstract_controller/base.rb:134)
usr.src.app.vendor.bundle.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.abstract_controller.base.RUBY$method$process$0(vendor/bundle/jruby/2.5.0/gems/actionpack-5.2.1/lib/abstract_controller/base.rb:134)
org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:91)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:90)
org.jruby.ir.runtime.IRRuntimeHelpers.unresolvedSuper(IRRuntimeHelpers.java:1151)
org.jruby.ir.runtime.IRRuntimeHelpers.unresolvedSuperSplatArgs(IRRuntimeHelpers.java:1133)
usr.src.app.vendor.bundle.jruby.$2_dot_5_dot_0.gems.actionview_minus_5_dot_2_dot_1.lib.action_view.rendering.invokeSuper5:-unknown-super-target-(vendor/bundle/jruby/2.5.0/gems/actionview-5.2.1/lib/action_view/rendering.rb:32)
usr.src.app.vendor.bundle.jruby.$2_dot_5_dot_0.gems.actionview_minus_5_dot_2_dot_1.lib.action_view.rendering.RUBY$method$process$0(vendor/bundle/jruby/2.5.0/gems/actionview-5.2.1/lib/action_view/rendering.rb:32)
org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:91)
org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:114)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:156)
org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:199)
org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:346)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:172)
usr.src.app.vendor.bundle.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_controller.metal.invokeOther2:process(vendor/bundle/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal.rb:191)
usr.src.app.vendor.bundle.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_controller.metal.RUBY$method$dispatch$0(vendor/bundle/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal.rb:191)
org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:143)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:221)
org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:215)
org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:390)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:234)
usr.src.app.vendor.bundle.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_controller.metal.invokeOther10:dispatch(vendor/bundle/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal.rb:252)
usr.src.app.vendor.bundle.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_controller.metal.RUBY$method$dispatch$0(vendor/bundle/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal.rb:252)
org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:143)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:221)
org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:215)
org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:390)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:234)
usr.src.app.vendor.bundle.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_dispatch.routing.route_set.invokeOther0:dispatch(vendor/bundle/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/routing/route_set.rb:52)
usr.src.app.vendor.bundle.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_dispatch.routing.route_set.RUBY$method$dispatch$0(vendor/bundle/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/routing/route_set.rb:52)
usr.src.app.vendor.bundle.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_dispatch.routing.route_set.RUBY$method$dispatch$0$__VARARGS__(vendor/bundle/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/routing/route_set.rb)
org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:91)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:90)
org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:173)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:72)
usr.src.app.vendor.bundle.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_dispatch.routing.route_set.invokeOther6:dispatch(vendor/bundle/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/routing/route_set.rb:34)
usr.src.app.vendor.bundle.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_dispatch.routing.route_set.RUBY$method$serve$0(vendor/bundle/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/routing/route_set.rb:34)
org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:117)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:156)
org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:199)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)
usr.src.app.vendor.bundle.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_dispatch.journey.router.invokeOther27:serve(vendor/bundle/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/journey/router.rb:52)
usr.src.app.vendor.bundle.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_dispatch.journey.router.RUBY$block$serve$1(vendor/bundle/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/journey/router.rb:52)
org.jruby.runtime.CompiledIRBlockBody.yieldDirect(CompiledIRBlockBody.java:146)
org.jruby.runtime.BlockBody.yield(BlockBody.java:114)
org.jruby.runtime.Block.yield(Block.java:165)
org.jruby.RubyArray.each(RubyArray.java:1792)
org.jruby.RubyArray$INVOKER$i$0$0$each.call(RubyArray$INVOKER$i$0$0$each.gen)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:149)
org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:158)
usr.src.app.vendor.bundle.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_dispatch.journey.router.invokeOther37:each(vendor/bundle/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/journey/router.rb:35)
usr.src.app.vendor.bundle.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_dispatch.journey
.router.RUBY$method$serve$0(vendor/bundle/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/journey/router
.rb:35)
org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:117)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:156)
org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:199)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)
usr.src.app.vendor.bundle.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_dispatch.routing.route_set.invokeOther5:serve(vendor/bundle/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/routing/route_set.rb:840)
usr.src.app.vendor.bundle.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_dispatch.routing.route_set.RUBY$method$call$0(vendor/bundle/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/routing/route_set.rb:840)
org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:117)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:156)
org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:199)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)
usr.src.app.vendor.bundle.jruby.$2_dot_5_dot_0.gems.rack_minus_attack_minus_5_dot_4_dot_2.lib.rack.attack.invokeOther18:call(vendor/bundle/jruby/2.5.0/gems/rack-attack-5.4.2/lib/rack/attack.rb:182)
usr.src.app.vendor.bundle.jruby.$2_dot_5_dot_0.gems.rack_minus_attack_minus_5_dot_4_dot_2.lib.rack.attack.RUBY$method$call$0(vendor/bundle/jruby/2.5.0/gems/rack-attack-5.4.2/lib/rack/attack.rb:182)
org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:117)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:156)
org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:199)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)
usr.src.app.vendor.bundle.jruby.$2_dot_5_dot_0.gems.i18n_minus_js_minus_3_dot_2_dot_0.lib.i18n.js.middleware.invokeOther3:call(vendor/bundle/jruby/2.5.0/gems/i18n-js-3.2.0/lib/i18n/js/middleware.rb:14)
usr.src.app.vendor.bundle.jruby.$2_dot_5_dot_0.gems.i18n_minus_js_minus_3_dot_2_dot_0.lib.i18n.js.middleware.RUBY$method$call$0(vendor/bundle/jruby/2.5.0/gems/i18n-js-3.2.0/lib/i18n/js/middleware.rb:14)
org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:117)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:156)
org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:199)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)
usr.src.app.vendor.bundle.jruby.$2_dot_5_dot_0.gems.rack_minus_2_dot_0_dot_6.lib.rack.tempfile_reaper.invokeOther8:call(vendor/bundle/jruby/2.5.0/gems/rack-2.0.6/lib/rack/tempfile_reaper.rb:15)
usr.src.app.vendor.bundle.jruby.$2_dot_5_dot_0.gems.rack_minus_2_dot_0_dot_6.lib.rack.tempfile_reaper.RUBY$method$call$0(vendor/bundle/jruby/2.5.0/gems/rack-2.0.6/lib/rack/tempfile_reaper.rb:15)
org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:117)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:156)
org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:199)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)
usr.src.app.vendor.bundle.jruby.$2_dot_5_dot_0.gems.rack_minus_2_dot_0_dot_6.lib.rack.etag.invokeOther5:call(vendor/bundle/jruby/2.5.0/gems/rack-2.0.6/lib/rack/etag.rb:25)
usr.src.app.vendor.bundle.jruby.$2_dot_5_dot_0.gems.rack_minus_2_dot_0_dot_6.lib.rack.etag.RUBY$method$call$0(vendor/bundle/jruby/2.5.0/gems/rack-2.0.6/lib/rack/etag.rb:25)
org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:117)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:156)
org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:199)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)
usr.src.app.vendor.bundle.jruby.$2_dot_5_dot_0.gems.rack_minus_2_dot_0_dot_6.lib.rack.conditional_get.invokeOther14:call(vendor/bundle/jruby/2.5.0/gems/rack-2.0.6/lib/rack/conditional_get.rb:38)
usr.src.app.vendor.bundle.jruby.$2_dot_5_dot_0.gems.rack_minus_2_dot_0_dot_6.lib.rack.conditional_get.RUBY$method$call$0(vendor/bundle/jruby/2.5.0/gems/rack-2.0.6/lib/rack/conditional_get.rb:38)
org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:117)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:156)
org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:199)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)
usr.src.app.vendor.bundle.jruby.$2_dot_5_dot_0.gems.rack_minus_2_dot_0_dot_6.lib.rack.head.invokeOther5:call(vendor/bundle/jruby/2.5.0/gems/rack-2.0.6/lib/rack/head.rb:12)
usr.src.app.vendor.bundle.jruby.$2_dot_5_dot_0.gems.rack_minus_2_dot_0_dot_6.lib.rack.head.RUBY$method$call$0(vendor/bundle/jruby/2.5.0/gems/rack-2.0.6/lib/rack/head.rb:12)
org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:117)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:156)
org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:199)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)
usr.src.app.vendor.bundle.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_dispatch.http.content_security_policy.invokeOther2:call(vendor/bundle/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/http/content_security_policy.rb:18)
usr.src.app.vendor.bundle.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_dispatch.http.content_security_policy.RUBY$method$call$0(vendor/bundle/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/http/content_security_policy.rb:18)
org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:117)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:156)
org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:199)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)
usr.src.app.vendor.bundle.jruby.$2_dot_5_dot_0.gems.warden_minus_1_dot_2_dot_8.lib.warden.manager.invokeOther4:call(vendor/bundle/jruby/2.5.0/gems/warden-1.2.8/lib/warden/manager.rb:36)
usr.src.app.vendor.bundle.jruby.$2_dot_5_dot_0.gems.warden_minus_1_dot_2_dot_8.lib.warden.manager.RUBY$block$call$1(vendor/bundle/jruby/2.5.0/gems/warden-1.2.8/lib/warden/manager.rb:36)
org.jruby.runtime.CompiledIRBlockBody.yieldDirect(CompiledIRBlockBody.java:146)
org.jruby.runtime.BlockBody.yield(BlockBody.java:114)
org.jruby.runtime.Block.yield(Block.java:165)
org.jruby.RubyContinuation.enter(RubyContinuation.java:108)
org.jruby.RubyKernel.rbCatch19Common(RubyKernel.java:1188)
org.jruby.RubyKernel.rbCatch19(RubyKernel.java:1181)
org.jruby.RubyKernel$INVOKER$s$rbCatch19.call(RubyKernel$INVOKER$s$rbCatch19.gen)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:180)
org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:189)
usr.src.app.vendor.bundle.jruby.$2_dot_5_dot_0.gems.warden_minus_1_dot_2_dot_8.lib.warden.manager.invokeOther1
7:catch(vendor/bundle/jruby/2.5.0/gems/warden-1.2.8/lib/warden/manager.rb:34)
usr.src.app.vendor.bundle.jruby.$2_dot_5_dot_0.gems.warden_minus_1_dot_2_dot_8.lib.warden.manager.RUBY$method$
call$0(vendor/bundle/jruby/2.5.0/gems/warden-1.2.8/lib/warden/manager.rb:34)
org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:117)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:156)
org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:199)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)
usr.src.app.vendor.bundle.jruby.$2_dot_5_dot_0.gems.rack_minus_2_dot_0_dot_6.lib.rack.session.abstract.id.invokeOther4:call(vendor/bundle/jruby/2.5.0/gems/rack-2.0.6/lib/rack/session/abstract/id.rb:232)
usr.src.app.vendor.bundle.jruby.$2_dot_5_dot_0.gems.rack_minus_2_dot_0_dot_6.lib.rack.session.abstract.id.RUBY$method$context$0(vendor/bundle/jruby/2.5.0/gems/rack-2.0.6/lib/rack/session/abstract/id.rb:232)
org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:91)
org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:114)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:156)
org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:199)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)
usr.src.app.vendor.bundle.jruby.$2_dot_5_dot_0.gems.rack_minus_2_dot_0_dot_6.lib.rack.session.abstract.id.invokeOther0:context(vendor/bundle/jruby/2.5.0/gems/rack-2.0.6/lib/rack/session/abstract/id.rb:226)
usr.src.app.vendor.bundle.jruby.$2_dot_5_dot_0.gems.rack_minus_2_dot_0_dot_6.lib.rack.session.abstract.id.RUBY$method$call$0(vendor/bundle/jruby/2.5.0/gems/rack-2.0.6/lib/rack/session/abstract/id.rb:226)
org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:117)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:156)
org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:199)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)
usr.src.app.vendor.bundle.jruby.$2_dot_5_dot_0.gems.actionpack_minus_5_dot_2_dot_1.lib.action_dispatch.middleware.cookies.invokeOther2:call(vendor/bundle/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/cookies.rb:670)
...
```
</details>

### PR DESCRIPTION
**Pull request by enebo**
My main commit explains most of the details of what changed.  See #5517 for more on what was broken.

### CODE REVIEW

**Comment by enebo** [comment]
ok found some errors to fix with full spec run

File: core/src/main/java/org/jruby/ir/IRBuilder.java [hunk 1]
```diff
@@ -3755,15 +3756,21 @@ public Operand buildReturn(ReturnNode returnNode) {
...
-            // 3. migrated closure (LJE) [dynamic]
-            // 4. eval/for (return) [static]
-            boolean definedWithinMethod = scope.getNearestMethod() != null;
-            if (!(scope instanceof IREvalScript) && !(scope instanceof IRFor)) addInstr(new CheckForLJEInstr(definedWithinMethod));
-            addInstr(new NonlocalReturnInstr(retVal,
-                    definedWithinMethod ? scope.getNearestMethod().getName() : manager.runtime.newSymbol("--none--")));
+            if (scope.isWithinEND()) {
+                // ENDs do not allow returns
+                addInstr(new ThrowExceptionInstr(IRException.RETURN_LocalJumpError));
+            } else {
```
Comment (headius) [inline core/src/main/java/org/jruby/ir/IRBuilder.java]: MRI doesn't appear to statically determine this, or else they just immediately bail out without propagating an exception. Probably doesn't matter that we actually raise? Maybe better?

```
[] ~/projects/jruby $ rvm ruby-2.5.3 do ruby -e 'END { begin; return; rescue Exception => e; p e; else; puts "not caught"; end }'
-e: unexpected return

[] ~/projects/jruby $ jruby -e 'END { begin; return; rescue Exception => e; p e; else; puts "not caught"; end }'
#<LocalJumpError: unexpected return>
```

File: core/src/main/java/org/jruby/ir/runtime/IRReturnJump.java [hunk 2]
```diff
@@ -1,19 +1,21 @@
...
+import org.jruby.ir.IRScope;
 
 public class IRReturnJump extends IRJump implements Unrescuable {
-    public final DynamicScope methodToReturnFrom;
+    public final IRScope returnScope;
+    public final IRScope methodToReturnFrom;
     public final Object returnValue;
 
-    private IRReturnJump(DynamicScope scopeToReturnFrom, Object rv) {
+    private IRReturnJump(IRScope returnScope, IRScope scopeToReturnFrom, Object rv) {
```
Comment (headius) [inline core/src/main/java/org/jruby/ir/runtime/IRReturnJump.java]: Naming is a little weird here...these mean the same thing in my head.

Comment (enebo) [reply core/src/main/java/org/jruby/ir/runtime/IRReturnJump.java]: returnScope is the scope where the return lives and scopeToReturnFrmo is where the return will exit from.  I am happy to change those though.

Comment (headius) [reply core/src/main/java/org/jruby/ir/runtime/IRReturnJump.java]: Maybe sourceScope and targetScope, or returnScope and targetScope? Entirely up to you, it's a minor issue.

File: core/src/main/java/org/jruby/ir/IRBuilder.java (hunk 1 above)
Comment (enebo) [reply core/src/main/java/org/jruby/ir/IRBuilder.java]: yeah hmm.  I did not consider the ability to catch. I do actually consider how we do it to be more correct but of course we emulate them...Even if we change this I would prefer to follow up on this in another PR/commit later.  This is better than our escape crash.  I also am not very concerned about this behavioral difference?

Comment (headius) [reply core/src/main/java/org/jruby/ir/IRBuilder.java]: Sounds find to me.

**Comment by enebo** [comment]
With these two reverts we pass all tests and one extra weird test I know fails...master also failed with exact same behavior.  Plan after landing this is to re-land these IRScope vs using DynamicScope commits and fix the last weird bug I know about.  The remaining issue known is about JITing the same define_method in a loop in the root scope.
